### PR TITLE
improvement(k8s/without-rbac): remove deploy method without rbac

### PR DESCRIPTION
**Pull request by maxgio92**
As for the issue #7, since the RBAC is the main authorization method and not using it for applications is deprecated, do not support it.

### CODE REVIEW

**Comment by maxgio92** [comment]
> Since there will be just on deploying method, I would like to move the content of [./k8s-using-daemonset/k8s-with-rbac](https://github.com/falcosecurity/contrib/tree/master/integrations/k8s-using-daemonset/k8s-with-rbac) on level up. I believe we don't need anymore the `k8s-with-rbac` in the path.
> 
> WDYT?
> 
> 
> 
> Except for that SGTM :+1: 

I totally agree

**Comment by leogr** [comment]
> > Since there will be just on deploying method, I would like to move the content of [./k8s-using-daemonset/k8s-with-rbac](https://github.com/falcosecurity/contrib/tree/master/integrations/k8s-using-daemonset/k8s-with-rbac) on level up. I believe we don't need anymore the `k8s-with-rbac` in the path.
> > WDYT?
> > Except for that SGTM +1
> 
> I totally agree

:+1: 

Could you move them in this PR, please?
I have put on hold just for that, then I think we can merge this.

Thank you!

**Comment by maxgio92** [comment]
> > > Since there will be just on deploying method, I would like to move the content of [./k8s-using-daemonset/k8s-with-rbac](https://github.com/falcosecurity/contrib/tree/master/integrations/k8s-using-daemonset/k8s-with-rbac) on level up. I believe we don't need anymore the `k8s-with-rbac` in the path.
> > > WDYT?
> > > Except for that SGTM +1
> > 
> > 
> > I totally agree
> 
> 
> 
> Could you move them in this PR, please?
> I have put on hold just for that, then I think we can merge this.
> 
> Thank you!

Done. This is a simple 's/k8s-with-rbac/\./g' :) I think that the current priority could be to "make the things work", before refactoring.

**Comment by fntlnz** [comment]
Why is poiana not merging this PR?

**Comment by leogr** [comment]
> Why is poiana not merging this PR?

I was thinking the same thing. Any idea?

**Comment by fntlnz** [comment]
Reopening to see if we can wake up our beloved bot

**Comment by leogr** [comment]
:eyes: 

/honk

**Comment by maxgio92** [comment]
It could depend on a resolved conflict with base branch?

I rembember to have seen Poiana noticed the need to rebase on the base branch, but I solved it via non fast-forward merge.

**Comment by leogr** [comment]
I see this PR has no conflicts with the base branch.

**Comment by maxgio92** [comment]
> I see this PR has no conflicts with the base branch.

Yes, not now as they are solved, but you can see that the second commit is an explicit merge commit :)

**Comment by fntlnz** [comment]
We have issues with Poiana https://github.com/falcosecurity/test-infra/issues/122

**Comment by fntlnz** [comment]
Merging manually.

**Comment by fntlnz** [comment]
Wait I can't
image

**Comment by fntlnz** [comment]
I think we need a manual rebase on top of master here @maxgio92

**Comment by maxgio92** [comment]
> I think we need a manual rebase on top of master here @maxgio92

Done, thanks

**Pull request merged**
