### PR TITLE
new(.github): add dependabot config

### PR DESCRIPTION
**Pull request by leogr**
Just experimenting

### CODE REVIEW

**Comment by leogr** [comment]
I closed this PR since

**Comment by maxgio92** [comment]
Can we do someting here @leogr?

**Comment by leogr** [comment]
> Can we do someting here @leogr?

I was just saying I wanted to close this PR, since I did not find the time to double-check the dependabot config, but it is working anyway (I don't know how).

Feel free to take a look, otherwise, we can close this PR. Let me know!

**Comment by maxgio92** [comment]
I think @leogr its already enabled at project/org level, and it's using the default configuration.

If we have specific needs I think we can introduce a customised config like this one

**Comment by leogr** [comment]
> I think @leogr its already enabled at project/org level, and it's using the default configuration.
> 
> If we have specific needs I think we can introduce a customised config like this one

You're right.

/close

**Pull request closed without merging**
