### PR TITLE
docs(README.md): add `/deploy`

### LINKED ISSUE #22: Update the root README
**What to document**

The root README should be updated to include the new _/deploy_ directory which contains the unofficial methods to deploy Falco.

/cc @leogr

### PR DESCRIPTION
**Pull request by leogr**
Also, alphabetically reorder the list.

Fixes #22 

/kind documentation
/cc @maxgio92

### CODE REVIEW

**Comment by maxgio92** [comment]
Ops! @leodido approval race condition :D

**Comment by leodido** [comment]
Hey @poiana don't be so lazy!

/honk

**Pull request merged**
